baseURL         = "https://thrive.localh0st.co.uk"
languageCode    = "en"
title           = "Twisted Thrive"

enableEmoji = false

[build]
  publishFuture = true

[menu]
  [[menu.main]]
    identifier = "exhibitions"
    name       = "Exhibitions"
    url        = "/exhibitions/"
    weight     = 1
  [[menu.main]]
    identifier = "gallery"
    name       = "Gallery"
    url        = "/gallery/"
    weight     = 2
  [[menu.main]]
    identifier = "journal"
    name       = "Journal"
    url        = "/journal/"
    weight     = 3
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 4

[params]
  description = "Contemporary art, exhibitions & visual experiments"
